--
-- (c) 2018-2019 Cloudera, Inc. All rights reserved.
--
--  This code is provided to you pursuant to your written agreement with Cloudera, which may be the terms of the
--  Affero General Public License version 3 (AGPLv3), or pursuant to a written agreement with a third party authorized
--  to distribute this code.  If you do not have a written agreement with Cloudera or with an authorized and
--  properly licensed third party, you do not have any rights to this code.
--
--  If this code is provided to you under the terms of the AGPLv3:
--   (A) CLOUDERA PROVIDES THIS CODE TO YOU WITHOUT WARRANTIES OF ANY KIND;
--   (B) CLOUDERA DISCLAIMS ANY AND ALL EXPRESS AND IMPLIED WARRANTIES WITH RESPECT TO THIS CODE, INCLUDING BUT NOT
--       LIMITED TO IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE;
--   (C) CLOUDERA IS NOT LIABLE TO YOU, AND WILL NOT DEFEND, INDEMNIFY, OR HOLD YOU HARMLESS FOR ANY CLAIMS ARISING
--       FROM OR RELATED TO THE CODE; AND
--   (D) WITH RESPECT TO YOUR EXERCISE OF ANY RIGHTS GRANTED TO YOU FOR THE CODE, CLOUDERA IS NOT LIABLE FOR ANY
--       DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES INCLUDING, BUT NOT LIMITED
--       TO, DAMAGES RELATED TO LOST REVENUE, LOST PROFITS, LOSS OF INCOME, LOSS OF BUSINESS ADVANTAGE OR
--       UNAVAILABILITY, OR LOSS OR CORRUPTION OF DATA.
--

CREATE TABLE FD_FLOW (
    ID VARCHAR(50) NOT NULL,
    AGENT_CLASS VARCHAR(200) NOT NULL,
    ROOT_PROCESS_GROUP_ID VARCHAR(50) NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK__FD_FLOW PRIMARY KEY (ID),
    CONSTRAINT UNIQUE__FD_FLOW__AGENT_CLASS UNIQUE (AGENT_CLASS)
);

CREATE TABLE FD_FLOW_EVENT (
    ID VARCHAR(50) NOT NULL,
    FLOW_ID VARCHAR(50) NOT NULL,
    FLOW_REVISION BIGINT NOT NULL,
    EVENT_TYPE VARCHAR(200) NOT NULL,
    EVENT_DESCRIPTION VARCHAR(4096) NOT NULL,
    FLOW_CONTENT LONGTEXT NOT NULL,
    FLOW_CONTENT_FORMAT VARCHAR(50) NOT NULL,
    COMPONENT_ID VARCHAR(50) NULL,
    USER_IDENTITY VARCHAR(4096) NOT NULL,
    NIFI_REGISTRY_URL VARCHAR(4096) NOT NULL,
    NIFI_REGISTRY_BUCKET_ID VARCHAR(50) NOT NULL,
    NIFI_REGISTRY_FLOW_ID VARCHAR(50) NOT NULL,
    NIFI_REGISTRY_FLOW_VERSION INT NOT NULL,
    LAST_PUBLISHED TIMESTAMP NULL,
    LAST_PUBLISHED_USER_IDENTITY VARCHAR(4096) NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK__FD_FLOW_EVENT PRIMARY KEY (ID),
    CONSTRAINT FK__FD_FLOW_EVENT__FLOW_ID FOREIGN KEY (FLOW_ID) REFERENCES FD_FLOW(ID) ON DELETE CASCADE,
    CONSTRAINT UNIQUE__FD_FLOW_EVENT__FLOW_ID_FLOW_REVISION UNIQUE (FLOW_ID, FLOW_REVISION)
);


